const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const target = path.join(__dirname, '.env');

if (fs.existsSync(target)) {
    console.log('[SETUP] Configuration already exists; nothing to do.');
    process.exit(0);
}

const terminal = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function ask(question) {
    return new Promise(resolve => terminal.question(question, answer => resolve(answer.trim())));
}

function envLine(name, value) {
    // JSON quoting safely preserves spaces and punctuation in Node's --env-file parser.
    return `${name}=${JSON.stringify(value)}`;
}

async function main() {
    console.log('');
    console.log('First-time server setup');
    console.log('-----------------------');
    console.log('Using the local PostgreSQL account postgres/postgres on 127.0.0.1:5432.');
    console.log('A separate RobloxChatLauncher database will be created automatically.');
    console.log('A Perspective API key is optional; without one, the built-in local safety policy is used.');
    console.log('');

    const databaseUrl = 'postgresql://postgres:postgres@127.0.0.1:5432/RobloxChatLauncher';
    const databaseSsl = false;

    const perspectiveKey = await ask('Google Perspective API key [optional]: ');

    const requestedPort = await ask('Server port [10000]: ');
    const port = requestedPort || '10000';
    const portNumber = Number(port);
    if (!Number.isInteger(portNumber) || portNumber < 1 || portNumber > 65535) {
        throw new Error('Port must be a whole number from 1 through 65535.');
    }

    const lines = [
        '# Generated by setup.js. Keep this file private.',
        envLine('PORT', port),
        envLine('DATABASE_URL', databaseUrl),
        envLine('DATABASE_SSL', databaseSsl ? 'true' : 'false'),
        envLine('PERSPECTIVE_API_KEY', perspectiveKey),
        envLine('RCL_ADMIN_KEY', crypto.randomBytes(32).toString('hex')),
        envLine('RCL_WRITE_KEY', crypto.randomBytes(32).toString('hex')),
        envLine('RCL_READ_KEY', crypto.randomBytes(32).toString('hex')),
        envLine('USER_SALT', crypto.randomBytes(32).toString('hex')),
        ''
    ];

    fs.writeFileSync(target, lines.join('\r\n'), { encoding: 'utf8', flag: 'wx' });
    console.log('');
    console.log(`[SETUP] Configuration saved to ${target}`);
    console.log('[SETUP] Private keys and the user salt were generated automatically.');
    console.log('[SETUP] The RobloxChatLauncher database will be created before startup.');
    console.log('[SETUP] Allow the selected TCP port through Windows Firewall for Radmin VPN.');
}

main()
    .catch(error => {
        console.error(`[SETUP] ${error.message}`);
        process.exitCode = 1;
    })
    .finally(() => terminal.close());
