const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require.resolve('./server.js'), 'utf8');
const start = source.indexOf('function broadcastRoster(');
const end = source.indexOf('\n}', start) + 2;
const channels = new Map();
let packet;
const context = { channels, WebSocket: { OPEN: 1 }, broadcastToChannel: (id, data) => { packet = { id, data }; } };
vm.createContext(context);
vm.runInContext(source.slice(start, end), context);
const a = { readyState: 1, memberId: 'a', senderName: 'Alice', robloxId: '123', secret: 'never export', sessionStartedAt: Date.now()-10000, previousTotalSeconds: 90, timezoneOffsetMinutes: -240, timezoneLabel: 'EDT' };
const b = { readyState: 1, memberId: 'b', senderName: 'Guest' };
channels.set('room1', new Set([a,b]));
channels.set('room2', new Set([{ ...a, memberId:'other' }]));
context.broadcastRoster('room1');
assert.equal(packet.data.members.length, 2);
assert.equal(packet.data.members[1].robloxId, null);
assert.ok(packet.data.members[0].sessionSeconds >= 9);
assert.ok(packet.data.members[0].totalSeconds >= 99);
assert.equal(packet.data.members[0].timezoneOffsetMinutes,-240);
assert.equal(packet.data.members[0].timezoneLabel,'EDT');
assert.equal(JSON.stringify(packet).includes('secret'), false);
assert.equal(JSON.stringify(packet).includes('other'), false);
channels.get('room1').delete(a);
context.broadcastRoster('room1');
assert.equal(packet.data.members.length, 1);
b.readyState = 3;
context.broadcastRoster('room1');
assert.equal(packet.data.members.length, 0);
console.log('Roster isolation, disconnect filtering, and public-field checks passed.');
