//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobloxChatLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChatUsageId { get { return (string)this["ChatUsageId"]; } set { this["ChatUsageId"] = value; } }
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 40")]
        public global::System.Drawing.Point WindowOffset {
            get {
                return ((global::System.Drawing.Point)(this["WindowOffset"]));
            }
            set {
                this["WindowOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 400")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("472, 297")]
        public global::System.Drawing.Size ChatContainerSize {
            get {
                return ((global::System.Drawing.Size)(this["ChatContainerSize"]));
            }
            set {
                this["ChatContainerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsVerified {
            get {
                return ((bool)(this["IsVerified"]));
            }
            set {
                this["IsVerified"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long RobloxUserId {
            get {
                return ((long)(this["RobloxUserId"]));
            }
            set {
                this["RobloxUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string MessageFilterPreference {
            get {
                return ((string)(this["MessageFilterPreference"]));
            }
            set {
                this["MessageFilterPreference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0069-04-20")]
        public global::System.DateTime LastUpdateCheckUTC {
            get {
                return ((global::System.DateTime)(this["LastUpdateCheckUTC"]));
            }
            set {
                this["LastUpdateCheckUTC"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerAddress {
            get { return ((string)(this["ServerAddress"])); }
            set { this["ServerAddress"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string ChatTheme {
            get { return ((string)(this["ChatTheme"])); }
            set { this["ChatTheme"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChatDragEnabled {
            get { return (bool)this["ChatDragEnabled"]; }
            set { this["ChatDragEnabled"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{}")]
        public string ChatDragOffsets {
            get { return (string)this["ChatDragOffsets"]; }
            set { this["ChatDragOffsets"] = value; }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{}")]
        public string ChatFrameSizes { get { return (string)this["ChatFrameSizes"]; } set { this["ChatFrameSizes"] = value; } }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("light")]
        public string ChatTextStyle { get { return (string)this["ChatTextStyle"]; } set { this["ChatTextStyle"] = value; } }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("classic")]
        public string Theme2014Mode { get { return (string)this["Theme2014Mode"]; } set { this["Theme2014Mode"] = value; } }
    }
}
