// Usage:
//     dotnet run .github/scripts/GenerateDocs.cs

#:package Microsoft.CodeAnalysis.CSharp@4.12.0

using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

// 1. Setup Paths
var cwd = Directory.GetCurrentDirectory();
var sourceFile = Path.Combine(cwd, "client", "ChatForm", "ChatForm.Commands.cs");
var outputFile = Path.Combine(cwd, "assets", "docs", "COMMANDS.md");

// 2. Validate Source
if (!File.Exists(sourceFile))
{
    throw new FileNotFoundException($"Oops! I couldn't find the file at {sourceFile}... Check the folder for me babe? 🎀");
}

// 3. Parse the Source Code
string sourceCode = File.ReadAllText(sourceFile);
SyntaxTree tree = CSharpSyntaxTree.ParseText(sourceCode);
var root = (CompilationUnitSyntax)tree.GetRoot();

// 4. Extraction Logic
var switchSections = root.DescendantNodes().OfType<SwitchSectionSyntax>();
var tableData = new List<Dictionary<string, string>>();
var allTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "Command", "Aliases" };

foreach (var section in switchSections)
{
    var firstLabel = section.Labels.FirstOrDefault();
    if (firstLabel == null)
        continue;

    // Find XML documentation
    var xmlTrivia = firstLabel.GetLeadingTrivia()
        .Select(t => t.GetStructure())
        .OfType<DocumentationCommentTriviaSyntax>()
        .FirstOrDefault();

    if (xmlTrivia != null)
    {
        var row = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        // --- Alias Logic ---
        var rawCommands = section.Labels
            .OfType<CaseSwitchLabelSyntax>()
            .Select(l => l.Value.ToString().Trim('\"'))
            .ToList();

        if (rawCommands.Any())
        {
            // 1. Primary Command: No backticks
            row["Command"] = rawCommands.First();

            // 2. Aliases: Wrapped in backticks, joined by commas
            row["Aliases"] = rawCommands.Count > 1
                ? string.Join(", ", rawCommands.Skip(1).Select(a => $"`{a}`"))
                : "-";
        }

        // --- Dynamic XML Logic ---
        var elements = xmlTrivia.Content.OfType<XmlElementSyntax>();
        foreach (var element in elements)
        {
            string tagName = element.StartTag.Name.ToString();
            // Clean up content: remove newlines and the "///" prefix that Roslyn sometimes leaves
            string rawContent = element.Content.ToString();
            string cleanContent = Regex.Replace(rawContent, @"\r?\n\s*///\s*", " ").Trim();

            row[tagName] = cleanContent;
            allTags.Add(tagName);
        }

        if (row.ContainsKey("summary"))
        {
            tableData.Add(row);
        }
    }
}

// 5. Generate Markdown Table
var sb = new StringBuilder();
sb.Append("<!-- DO NOT EDIT THIS DOC; IT IS AUTO-GENERATED BY CI -->\r\n");
sb.Append("<!-- Changes to this file will be lost if the file is regenerated -->\r\n");
sb.AppendLine("# Command Documentation\r\n");

if (tableData.Any())
{
    // Fixed order: Command first, then Aliases, then Summary, then everything else
    var columns = new List<string> { "Command", "Aliases", "summary" };

    // Add any other custom tags found (e.g., <permission>, <example>)
    var extraTags = allTags
        .Where(t => !columns.Contains(t, StringComparer.OrdinalIgnoreCase))
        .OrderBy(t => t);
    columns.AddRange(extraTags);

    // Header Row
    sb.AppendLine("| " + string.Join(" | ", columns.Select(c => char.ToUpper(c[0]) + c.Substring(1))) + " |");
    sb.AppendLine("| " + string.Join(" | ", columns.Select(_ => "---")) + " |");

    // Data Rows
    foreach (var row in tableData)
    {
        var line = columns.Select(col => row.ContainsKey(col) && !string.IsNullOrWhiteSpace(row[col])
            ? row[col]
            : "-");
        sb.AppendLine("| " + string.Join(" | ", line) + " |");
    }
}

// 6. Write File
var outputDir = Path.GetDirectoryName(outputFile);
if (!string.IsNullOrEmpty(outputDir) && !Directory.Exists(outputDir))
{
    Directory.CreateDirectory(outputDir);
}

File.WriteAllText(outputFile, sb.ToString());

Console.WriteLine($"Generated {tableData.Count} commands with columns: {string.Join(", ", allTags)} at {outputFile}! 💝");
